import matplotlib.pyplot as plt
import numpy as np
t = np.array([1,2,3,4])
plt.plot(t**2,t,color="cyan",label="label-1")
plt.plot(t**3,t,color="green",label="label-2")
plt.minorticks_on()
plt.xlabel("x label")
plt.ylabel("y label")
plt.title("first plot")
plt.grid()
plt.legend()
#plt.tick_params(length=5)
#plt.tick_params(axis="x",length=10)
#plt.tick_params(axis="x",width=10)
plt.tick_params(width=10,color="blue",pad=10)
#plt.tick_params(axis="x",color="red",direction="in",length=10)
#plt.tick_params(axis="y",color="y",direction="inout",length=10,which="minor")
plt.tick_params(right=True)
plt.show()